# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ConfirmExitDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmExitDialogWindow(object):
    def setupUi(self, ConfirmExitDialogWindow):
        ConfirmExitDialogWindow.setObjectName("ConfirmExitDialogWindow")
        ConfirmExitDialogWindow.resize(282, 124)
        self.label = QtWidgets.QLabel(ConfirmExitDialogWindow)
        self.label.setGeometry(QtCore.QRect(30, 35, 221, 20))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfirmExitDialogWindow)
        self.buttonBox.setGeometry(QtCore.QRect(50, 70, 161, 41))
        self.buttonBox.setStyleSheet("            /* 按钮通用样式 */\n"
"            QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 40px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"            }")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ConfirmExitDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmExitDialogWindow)

    def retranslateUi(self, ConfirmExitDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmExitDialogWindow.setWindowTitle(_translate("ConfirmExitDialogWindow", "确认退出"))
        self.label.setText(_translate("ConfirmExitDialogWindow", "脚本运行中，确定要中止并退出程序吗？"))
