# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ConfirmExitDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmExitDialogWindow(object):
    def setupUi(self, ConfirmExitDialog):
        ConfirmExitDialog.setObjectName("ConfirmExitDialog")
        ConfirmExitDialog.resize(282, 124)
        self.label = QtWidgets.QLabel(ConfirmExitDialog)
        self.label.setGeometry(QtCore.QRect(30, 35, 221, 20))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfirmExitDialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 70, 161, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ConfirmExitDialog)
        QtCore.QMetaObject.connectSlotsByName(ConfirmExitDialog)

    def retranslateUi(self, ConfirmExitDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfirmExitDialog.setWindowTitle(_translate("ConfirmExitDialog", "确认退出"))
        self.label.setText(_translate("ConfirmExitDialog", "脚本运行中，确定要中止并退出程序吗？"))

        # 设置按钮文本为中文
        ok_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel)
        ok_button.setText(_translate("LoadScriptDialogWindow", "确定"))
        cancel_button.setText(_translate("LoadScriptDialogWindow", "取消"))