# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EncyclopediaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EncyclopediaWindow(object):
    def setupUi(self, EncyclopediaWindow):
        EncyclopediaWindow.setObjectName("EncyclopediaWindow")
        EncyclopediaWindow.resize(961, 434)
        EncyclopediaWindow.setMinimumSize(QtCore.QSize(961, 434))
        EncyclopediaWindow.setMaximumSize(QtCore.QSize(961, 434))
        self.centralwidget = QtWidgets.QWidget(EncyclopediaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(20, 20, 681, 41))
        self.searchEdit.setStyleSheet("            /* 输入框样式 */\n"
"            QLineEdit {\n"
"                border: 1px solid #D8DEE9;\n"
"                padding: 5px;\n"
"                border-radius: 3px;\n"
"            }")
        self.searchEdit.setClearButtonEnabled(True)
        self.searchEdit.setObjectName("searchEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 921, 331))
        self.tableWidget.setMinimumSize(QtCore.QSize(921, 331))
        self.tableWidget.setMaximumSize(QtCore.QSize(921, 331))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.TurnToCalculator = QtWidgets.QPushButton(self.centralwidget)
        self.TurnToCalculator.setGeometry(QtCore.QRect(730, 20, 201, 41))
        self.TurnToCalculator.setStyleSheet("            /* 按钮通用样式 */\n"
"            QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 80px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"            }")
        self.TurnToCalculator.setObjectName("TurnToCalculator")
        EncyclopediaWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EncyclopediaWindow)
        QtCore.QMetaObject.connectSlotsByName(EncyclopediaWindow)

    def retranslateUi(self, EncyclopediaWindow):
        _translate = QtCore.QCoreApplication.translate
        EncyclopediaWindow.setWindowTitle(_translate("EncyclopediaWindow", "精灵大全"))
        self.searchEdit.setPlaceholderText(_translate("EncyclopediaWindow", "输入精灵名称/序号进行搜索"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EncyclopediaWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("EncyclopediaWindow", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("EncyclopediaWindow", "体力"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("EncyclopediaWindow", "攻击"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("EncyclopediaWindow", "特攻"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("EncyclopediaWindow", "防御"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("EncyclopediaWindow", "特防"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("EncyclopediaWindow", "速度"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("EncyclopediaWindow", "总和"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("EncyclopediaWindow", "学习力掉落"))
        self.TurnToCalculator.setText(_translate("EncyclopediaWindow", "进入计算器"))
