# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_IndividualValueCalculatorWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndividualValueCalculatorWindow(object):
    def setupUi(self, IndividualValueCalculatorWindow):
        IndividualValueCalculatorWindow.setObjectName("IndividualValueCalculatorWindow")
        IndividualValueCalculatorWindow.resize(400, 160)
        IndividualValueCalculatorWindow.setMinimumSize(QtCore.QSize(400, 160))
        IndividualValueCalculatorWindow.setMaximumSize(QtCore.QSize(400, 160))
        IndividualValueCalculatorWindow.setStyleSheet("/* 按钮通用样式 */\n"
"                QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 80px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"                }\n"
"\n"
"                QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"                }\n"
"\n"
"                /* 输入框样式 */\n"
"                QLineEdit {\n"
"                border: 1px solid #D8DEE9;\n"
"                padding: 5px;\n"
"                border-radius: 3px;\n"
"                }\n"
"\n"
"                /* 标签样式 */\n"
"                QLabel {\n"
"                color: #4A5665;\n"
"                font-size: 13px;\n"
"                }\n"
"            ")
        self.centralwidget = QtWidgets.QWidget(IndividualValueCalculatorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CalculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CalculateButton.setGeometry(QtCore.QRect(120, 100, 151, 41))
        self.CalculateButton.setObjectName("CalculateButton")
        self.TextLable_3 = QtWidgets.QLabel(self.centralwidget)
        self.TextLable_3.setGeometry(QtCore.QRect(260, 30, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TextLable_3.setFont(font)
        self.TextLable_3.setObjectName("TextLable_3")
        self.TextLable_1 = QtWidgets.QLabel(self.centralwidget)
        self.TextLable_1.setGeometry(QtCore.QRect(20, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TextLable_1.setFont(font)
        self.TextLable_1.setObjectName("TextLable_1")
        self.TextLable_2 = QtWidgets.QLabel(self.centralwidget)
        self.TextLable_2.setGeometry(QtCore.QRect(140, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TextLable_2.setFont(font)
        self.TextLable_2.setObjectName("TextLable_2")
        self.IndividualValueEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.IndividualValueEdit_1.setGeometry(QtCore.QRect(70, 20, 50, 35))
        self.IndividualValueEdit_1.setPlaceholderText("")
        self.IndividualValueEdit_1.setObjectName("IndividualValueEdit_1")
        self.IndividualValueEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.IndividualValueEdit_2.setGeometry(QtCore.QRect(190, 20, 50, 35))
        self.IndividualValueEdit_2.setPlaceholderText("")
        self.IndividualValueEdit_2.setObjectName("IndividualValueEdit_2")
        self.IndividualValueEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.IndividualValueEdit_3.setGeometry(QtCore.QRect(320, 20, 50, 35))
        self.IndividualValueEdit_3.setPlaceholderText("")
        self.IndividualValueEdit_3.setObjectName("IndividualValueEdit_3")
        self.TextLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.TextLabel_4.setGeometry(QtCore.QRect(90, 70, 241, 15))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.TextLabel_4.setFont(font)
        self.TextLabel_4.setObjectName("TextLabel_4")
        IndividualValueCalculatorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(IndividualValueCalculatorWindow)
        QtCore.QMetaObject.connectSlotsByName(IndividualValueCalculatorWindow)

    def retranslateUi(self, IndividualValueCalculatorWindow):
        _translate = QtCore.QCoreApplication.translate
        IndividualValueCalculatorWindow.setWindowTitle(_translate("IndividualValueCalculatorWindow", "融合个体计算器"))
        self.CalculateButton.setText(_translate("IndividualValueCalculatorWindow", "开始计算"))
        self.TextLable_3.setText(_translate("IndividualValueCalculatorWindow", "保底个体"))
        self.TextLable_1.setText(_translate("IndividualValueCalculatorWindow", "主个体"))
        self.TextLable_2.setText(_translate("IndividualValueCalculatorWindow", "副个体"))
        self.IndividualValueEdit_1.setText(_translate("IndividualValueCalculatorWindow", "0"))
        self.IndividualValueEdit_2.setText(_translate("IndividualValueCalculatorWindow", "0"))
        self.IndividualValueEdit_3.setText(_translate("IndividualValueCalculatorWindow", "0"))
        self.TextLabel_4.setText(_translate("IndividualValueCalculatorWindow", "融合后个体将在保底个体基础上进行随机"))
