# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(487, 296)
        LoginWindow.setMinimumSize(QtCore.QSize(487, 296))
        LoginWindow.setMaximumSize(QtCore.QSize(487, 296))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setAutoFillBackground(False)
        self.accountEdit = QtWidgets.QLineEdit(LoginWindow)
        self.accountEdit.setGeometry(QtCore.QRect(90, 110, 290, 40))
        self.accountEdit.setObjectName("accountEdit")
        self.passwordEdit = QtWidgets.QLineEdit(LoginWindow)
        self.passwordEdit.setGeometry(QtCore.QRect(90, 170, 290, 40))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.confirmButton = QtWidgets.QPushButton(LoginWindow)
        self.confirmButton.setGeometry(QtCore.QRect(170, 230, 121, 51))
        self.confirmButton.setObjectName("confirmButton")
        self.label = QtWidgets.QLabel(LoginWindow)
        self.label.setGeometry(QtCore.QRect(185, 10, 91, 81))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("image: url(:/login_logo/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录"))
        self.accountEdit.setPlaceholderText(_translate("LoginWindow", "请输入账号"))
        self.passwordEdit.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.confirmButton.setText(_translate("LoginWindow", "登录/注册"))
import login_logo_rc
