# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_LoadScriptDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadScriptDialogWindow(object):
    def setupUi(self, LoadScriptDialogWindow):
        LoadScriptDialogWindow.setObjectName("LoadScriptDialogWindow")
        LoadScriptDialogWindow.resize(400, 150)
        self.filePathLabel = QtWidgets.QLabel(LoadScriptDialogWindow)
        self.filePathLabel.setGeometry(QtCore.QRect(20, 9, 361, 41))
        self.filePathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filePathLabel.setObjectName("filePathLabel")
        self.selectFileButton = QtWidgets.QPushButton(LoadScriptDialogWindow)
        self.selectFileButton.setGeometry(QtCore.QRect(140, 60, 110, 31))
        self.selectFileButton.setStyleSheet("            /* 按钮通用样式 */\n"
"            QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 80px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"            }")
        self.selectFileButton.setObjectName("selectFileButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(LoadScriptDialogWindow)
        self.buttonBox.setGeometry(QtCore.QRect(110, 100, 171, 41))
        self.buttonBox.setStyleSheet("            /* 按钮通用样式 */\n"
"            QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 50px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"            }")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(LoadScriptDialogWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadScriptDialogWindow)

    def retranslateUi(self, LoadScriptDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadScriptDialogWindow.setWindowTitle(_translate("LoadScriptDialogWindow", "加载自定义脚本"))
        self.filePathLabel.setText(_translate("LoadScriptDialogWindow", "未选择文件"))
        self.selectFileButton.setText(_translate("LoadScriptDialogWindow", "选择脚本文件"))

        # 设置按钮文本为中文
        ok_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel)
        ok_button.setText(_translate("LoadScriptDialogWindow", "确定"))
        cancel_button.setText(_translate("LoadScriptDialogWindow", "取消"))