# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(958, 578)
        MainWindow.setMinimumSize(QtCore.QSize(958, 578))
        MainWindow.setMaximumSize(QtCore.QSize(958, 578))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(5.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* 按钮通用样式 */\n"
"                QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 80px;\n"
"                }\n"
"\n"
"                QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"                }\n"
"\n"
"                QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"                }\n"
"                /* 输入框样式 */\n"
"                QLineEdit {\n"
"                border: 1px solid #D8DEE9;\n"
"                padding: 5px;\n"
"                border-radius: 3px;\n"
"                }\n"
"\n"
"                /* 标签样式 */\n"
"                QLabel {\n"
"                color: #4A5665;\n"
"                font-size: 13px;\n"
"                }\n"
"            ")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.ReFresh = QtWidgets.QAction(MainWindow)
        self.ReFresh.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.ReFresh.setFont(font)
        self.ReFresh.setObjectName("ReFresh")
        self.SpeedChange = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.SpeedChange.setFont(font)
        self.SpeedChange.setObjectName("SpeedChange")
        self.SoundOff = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.SoundOff.setFont(font)
        self.SoundOff.setObjectName("SoundOff")
        self.StayTop = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.StayTop.setFont(font)
        self.StayTop.setObjectName("StayTop")
        self.CleanCache = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.CleanCache.setFont(font)
        self.CleanCache.setObjectName("CleanCache")
        self.Encyclopedia = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.Encyclopedia.setFont(font)
        self.Encyclopedia.setObjectName("Encyclopedia")
        self.Calculator = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.Calculator.setFont(font)
        self.Calculator.setObjectName("Calculator")
        self.EnableScripts = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.EnableScripts.setFont(font)
        self.EnableScripts.setObjectName("EnableScripts")
        self.LoadCustomScript = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.LoadCustomScript.setFont(font)
        self.LoadCustomScript.setObjectName("LoadCustomScript")
        self.About = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.About.setFont(font)
        self.About.setObjectName("About")
        self.UpdateLog = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        self.UpdateLog.setFont(font)
        self.UpdateLog.setObjectName("UpdateLog")
        self.menu.addAction(self.ReFresh)
        self.menu.addAction(self.SpeedChange)
        self.menu.addAction(self.SoundOff)
        self.menu.addAction(self.StayTop)
        self.menu.addAction(self.CleanCache)
        self.menu_2.addAction(self.EnableScripts)
        self.menu_2.addAction(self.LoadCustomScript)
        self.menu_3.addAction(self.Encyclopedia)
        self.menu_3.addAction(self.Calculator)
        self.menu_4.addAction(self.About)
        self.menu_4.addAction(self.UpdateLog)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "茶杯登录器"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "脚本"))
        self.menu_3.setTitle(_translate("MainWindow", "功能"))
        self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.ReFresh.setText(_translate("MainWindow", "刷新"))
        self.SpeedChange.setText(_translate("MainWindow", "变速"))
        self.SoundOff.setText(_translate("MainWindow", "静音"))
        self.StayTop.setText(_translate("MainWindow", "置顶"))
        self.CleanCache.setText(_translate("MainWindow", "清理缓存"))
        self.Encyclopedia.setText(_translate("MainWindow", "精灵大全"))
        self.Calculator.setText(_translate("MainWindow", "精灵计算器"))
        self.EnableScripts.setText(_translate("MainWindow", "启用脚本(F9)"))
        self.LoadCustomScript.setText(_translate("MainWindow", "加载脚本"))
        self.About.setText(_translate("MainWindow", "登录器"))
        self.UpdateLog.setText(_translate("MainWindow", "更新日志"))
