# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OnStartDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OnStartDialogWindow(object):
    def setupUi(self, OnStartDialogWindow):
        OnStartDialogWindow.setObjectName("OnStartDialogWindow")
        OnStartDialogWindow.resize(720, 535)
        OnStartDialogWindow.setMinimumSize(QtCore.QSize(720, 535))
        OnStartDialogWindow.setMaximumSize(QtCore.QSize(720, 535))
        OnStartDialogWindow.setStyleSheet("QDialog {\n"
"                background: #ffffff;\n"
"                font-family: \"Microsoft YaHei\";\n"
"                }\n"
"            ")
        self.label_title = QtWidgets.QLabel(OnStartDialogWindow)
        self.label_title.setGeometry(QtCore.QRect(228, 10, 251, 42))
        self.label_title.setStyleSheet("QLabel {\n"
"                    color: #2c3e50;\n"
"                    font-size: 18px;\n"
"                    font-weight: bold;\n"
"                    padding: 12px 0;\n"
"                    }\n"
"                ")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.scrollArea = QtWidgets.QScrollArea(OnStartDialogWindow)
        self.scrollArea.setGeometry(QtCore.QRect(20, 60, 681, 411))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"                    border: 1px solid #dcdde1;\n"
"                    border-radius: 4px;\n"
"                    background: #f8f9fa;\n"
"                    }\n"
"                    QScrollBar:vertical {\n"
"                    width: 8px;\n"
"                    background: transparent;\n"
"                    }\n"
"                    QScrollBar::handle:vertical {\n"
"                    background: #c8d6e5;\n"
"                    border-radius: 4px;\n"
"                    min-height: 30px;\n"
"                    }\n"
"                ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 662, 1758))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_content = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_content.setStyleSheet("QLabel {\n"
"                                    color: #4a5568;\n"
"                                    font-size: 13px;\n"
"                                    line-height: 1.8;\n"
"                                    padding: 20px;\n"
"                                    }\n"
"                                    .warning {\n"
"                                    color: #e74c3c;\n"
"                                    font-weight: bold;\n"
"                                    font-size: 14px;\n"
"                                    }\n"
"                                ")
        self.label_content.setAlignment(QtCore.Qt.AlignTop)
        self.label_content.setWordWrap(True)
        self.label_content.setObjectName("label_content")
        self.verticalLayout_2.addWidget(self.label_content)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buttonBox = QtWidgets.QDialogButtonBox(OnStartDialogWindow)
        self.buttonBox.setGeometry(QtCore.QRect(250, 480, 211, 41))
        self.buttonBox.setStyleSheet("/* 按钮通用样式 */\n"
"                    QPushButton {\n"
"                    background-color: #5E81AC;\n"
"                    color: white;\n"
"                    border: none;\n"
"                    padding: 8px 15px;\n"
"                    border-radius: 4px;\n"
"                    min-width: 70px;\n"
"                    }\n"
"\n"
"                    QPushButton:hover {\n"
"                    background-color: #81A1C1;\n"
"                    }\n"
"\n"
"                    QPushButton:pressed {\n"
"                    background-color: #4C6A8C;\n"
"                    }\n"
"                ")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(OnStartDialogWindow)
        self.buttonBox.accepted.connect(OnStartDialogWindow.accept)
        self.buttonBox.rejected.connect(OnStartDialogWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(OnStartDialogWindow)

    def retranslateUi(self, OnStartDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        OnStartDialogWindow.setWindowTitle(_translate("OnStartDialogWindow", "用户服务协议"))
        self.label_title.setText(_translate("OnStartDialogWindow", "《用户服务协议》"))
        self.label_content.setText(_translate("OnStartDialogWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html>\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<style type=\"text/css\">\n"
"body {\n"
"    font-family: \'Microsoft YaHei\', \'SimSun\';\n"
"    line-height: 1.8;\n"
"    color: #2c3e50;\n"
"    margin: 2rem;\n"
"}\n"
"\n"
".warning-block {\n"
"    background: #f8d7da;\n"
"    border-left: 4px solid #dc3545;\n"
"    padding: 1.5rem;\n"
"    margin: 2rem 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
".section-title {\n"
"    color: #2c3e50;\n"
"    font-size: 1.5rem;\n"
"    border-bottom: 2px solid #3498db;\n"
"    padding-bottom: 0.5rem;\n"
"    margin: 2rem 0 1.5rem;\n"
"}\n"
"\n"
".subsection-title {\n"
"    color: #2c3e50;\n"
"    font-size: 1.3rem;\n"
"    margin: 1.8rem 0 1.2rem;\n"
"}\n"
"\n"
".article-content {\n"
"    margin: 1rem 0;\n"
"    text-indent: 2em;\n"
"}\n"
"\n"
"ul {\n"
"    margin: 1rem 0;\n"
"    padding-left: 2.5rem;\n"
"}\n"
"\n"
"li {\n"
"    margin: 0.8rem 0;\n"
"    list-style-type: square;\n"
"}\n"
"\n"
".red-alert {\n"
"    color: #dc3545;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
".code-block {\n"
"    background: #f8f9fa;\n"
"    padding: 1rem;\n"
"    border-radius: 4px;\n"
"    font-family: Consolas, monospace;\n"
"    margin: 1rem 0;\n"
"}\n"
"\n"
".final-notice {\n"
"    text-align: center;\n"
"    font-size: 1.2rem;\n"
"    margin: 3rem 0;\n"
"    padding: 2rem;\n"
"    background: #e9ecef;\n"
"    border-radius: 8px;\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div class=\"warning-block\">\n"
"    <p class=\"red-alert\">⚠ 重要警示：本软件为完全免费工具，通过任何付费途径获得均为上当受骗！</p>\n"
"</div>\n"
"\n"
"<h1 class=\"section-title\">用户服务协议</h1>\n"
"\n"
"<h2 class=\"subsection-title\">重要提示</h2>\n"
"<p class=\"article-content\">本协议是用户（下称\"您\"或\"用户\"）与茶杯登录器之间的法律协议，茶杯登录器将按照本协议约定为您提供服务。\"茶杯登录器\"指茶杯登录器及其相关服务、制作团队或个人。</p>\n"
"\n"
"<h2 class=\"subsection-title\">一、软件性质</h2>\n"
"<div class=\"warning-block\">\n"
"    <p class=\"red-alert\">※ 本软件仅供学习交流使用，禁止用于商业用途 ※</p>\n"
"</div>\n"
"<p class=\"article-content\">1.1 茶杯登录器是针对游戏《赛尔号》的辅助工具，提供日常登录、游戏优化、数据计算等功能，非作弊外挂。</p>\n"
"<p class=\"article-content\">1.2 本软件为免费开源项目，属玩家自发制作的公益工具，开发目的为提升游戏体验，不收取任何费用。</p>\n"
"\n"
"<h2 class=\"subsection-title\">二、版权声明</h2>\n"
"<p class=\"article-content\">2.1 软件源代码著作权归作者所有（图标素材除外）</p>\n"
"<p class=\"article-content\">2.2 游戏主体及素材版权归属上海淘米网络科技有限公司</p>\n"
"\n"
"<h2 class=\"subsection-title\">三、服务条款</h2>\n"
"<p class=\"article-content\">3.1 服务范围包括：</p>\n"
"<ul>\n"
"    <li>茶杯登录器主体程序</li>\n"
"    <li>精灵大全/计算器等扩展功能</li>\n"
"    <li>游戏攻略与科普内容</li>\n"
"    <li>多终端适配版本</li>\n"
"</ul>\n"
"<p class=\"article-content\">3.2 禁止通过非法手段分离软件功能</p>\n"
"<p class=\"article-content\">3.3 仅限官方指定渠道下载使用</p>\n"
"\n"
"<h2 class=\"subsection-title\">四、用户责任</h2>\n"
"<p class=\"article-content\">4.1 需遵守以下法律法规：</p>\n"
"<ul>\n"
"    <li>《中华人民共和国网络安全法》</li>\n"
"    <li>《计算机软件保护条例》</li>\n"
"    <li>《信息网络传播权保护条例》</li>\n"
"</ul>\n"
"<p class=\"article-content\">4.2 禁止行为包括：</p>\n"
"<ul>\n"
"    <li>利用软件进行游戏作弊</li>\n"
"    <li>商业性使用或二次销售</li>\n"
"    <li>反向工程或恶意修改</li>\n"
"</ul>\n"
"\n"
"<h2 class=\"subsection-title\">五、数据安全</h2>\n"
"<p class=\"article-content\">5.1 本地存储采用明文记录账号（不含密码）</p>\n"
"<p class=\"article-content\">5.2 建议安全措施：</p>\n"
"<ul>\n"
"    <li>定期修改游戏密码</li>\n"
"    <li>避免公共设备保存信息</li>\n"
"    <li>使用系统加密工具</li>\n"
"</ul>\n"
"\n"
"<h2 class=\"subsection-title\">六、免责声明</h2>\n"
"<p class=\"article-content\">6.1 不承担责任的情形：</p>\n"
"<ul>\n"
"    <li>软件漏洞导致的数据异常</li>\n"
"    <li>版本不兼容问题</li>\n"
"    <li>用户自行修改引发的故障</li>\n"
"    <li>网络问题导致的登录失败</li>\n"
"</ul>\n"
"\n"
"<div class=\"final-notice\">\n"
"    <p class=\"red-alert\">【重要提示】本软件完全免费，谨防诈骗！</p>\n"
"    <p class=\"red-alert\">【使用确认】继续操作即视为接受全部条款</p>\n"
"</div>\n"
"\n"
"</body>\n"
"</html>"))
