# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OnStartDialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OnStartDialogWindow(object):
    def setupUi(self, OnStartDialogWindow):
        OnStartDialogWindow.setObjectName("OnStartDialogWindow")
        OnStartDialogWindow.resize(720, 535)
        OnStartDialogWindow.setStyleSheet("QDialog {\n"
"                background: #ffffff;\n"
"                font-family: \"Microsoft YaHei\";\n"
"                }\n"
"            ")
        self.label_title = QtWidgets.QLabel(OnStartDialogWindow)
        self.label_title.setGeometry(QtCore.QRect(250, 10, 209, 42))
        self.label_title.setStyleSheet("QLabel {\n"
"                    color: #2c3e50;\n"
"                    font-size: 18px;\n"
"                    font-weight: bold;\n"
"                    padding: 12px 0;\n"
"                    }\n"
"                ")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.scrollArea = QtWidgets.QScrollArea(OnStartDialogWindow)
        self.scrollArea.setGeometry(QtCore.QRect(20, 60, 681, 411))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"                    border: 1px solid #dcdde1;\n"
"                    border-radius: 4px;\n"
"                    background: #f8f9fa;\n"
"                    }\n"
"                    QScrollBar:vertical {\n"
"                    width: 8px;\n"
"                    background: transparent;\n"
"                    }\n"
"                    QScrollBar::handle:vertical {\n"
"                    background: #c8d6e5;\n"
"                    border-radius: 4px;\n"
"                    min-height: 30px;\n"
"                    }\n"
"                ")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 662, 1191))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_content = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_content.setStyleSheet("QLabel {\n"
"                                    color: #4a5568;\n"
"                                    font-size: 13px;\n"
"                                    line-height: 1.8;\n"
"                                    padding: 20px;\n"
"                                    }\n"
"                                    .warning {\n"
"                                    color: #e74c3c;\n"
"                                    font-weight: bold;\n"
"                                    font-size: 14px;\n"
"                                    }\n"
"                                ")
        self.label_content.setAlignment(QtCore.Qt.AlignTop)
        self.label_content.setWordWrap(True)
        self.label_content.setObjectName("label_content")
        self.verticalLayout_2.addWidget(self.label_content)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.buttonBox = QtWidgets.QDialogButtonBox(OnStartDialogWindow)
        self.buttonBox.setGeometry(QtCore.QRect(250, 480, 211, 41))
        self.buttonBox.setStyleSheet("/* 按钮通用样式 */\n"
"                    QPushButton {\n"
"                    background-color: #5E81AC;\n"
"                    color: white;\n"
"                    border: none;\n"
"                    padding: 8px 15px;\n"
"                    border-radius: 4px;\n"
"                    min-width: 70px;\n"
"                    }\n"
"\n"
"                    QPushButton:hover {\n"
"                    background-color: #81A1C1;\n"
"                    }\n"
"\n"
"                    QPushButton:pressed {\n"
"                    background-color: #4C6A8C;\n"
"                    }\n"
"                ")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(OnStartDialogWindow)
        self.buttonBox.accepted.connect(OnStartDialogWindow.accept)
        self.buttonBox.rejected.connect(OnStartDialogWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(OnStartDialogWindow)

    def retranslateUi(self, OnStartDialogWindow):
        _translate = QtCore.QCoreApplication.translate
        OnStartDialogWindow.setWindowTitle(_translate("OnStartDialogWindow", "用户协议与免责声明"))
        self.label_title.setText(_translate("OnStartDialogWindow", "《用户协议与免责声明》"))
        self.label_content.setText(_translate("OnStartDialogWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">⚠重要警示：本软件为完全免费工具，通过任何付费途径获得均为上当受骗！</span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<h3 style=\" margin-top:20px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">重要提示</span><span style=\" font-size:large; font-weight:600;\">                                     </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">1. 本软件为《赛尔号》游戏爱好者开发的第三方工具</span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">一、软件性质</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#e74c3c;\">※ 本软件仅供学习交流使用，禁止用于商业用途 ※</span><span style=\" font-size:medium; font-weight:600;\"> </span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#e74c3c;\">1.1本软件遵循MIT开源协议，禁止用于商业用途及任何非法场景</span><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\"><br /></span><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#e74c3c;\">1.2用户使用本软件需遵守《网络安全法》及相关法律法规</span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">二、用户责任</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">2.1 使用者承诺：</span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">不用于任何违反《计算机软件保护条例》的行为                                    </span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                                                        </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">不将该软件用于商业运营、游戏代练等营利行为</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">在游戏允许范围内进行脚本操作                                    </span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                                                        </span></li></ul>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">三、数据安全</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">3.1本地存储的账号信息（login.json）为明文存储<br />3.2 建议采取以下安全措施：</span><span style=\" font-size:13px;\">                                                                        </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">定期修改游戏密码</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">不在公共设备保存登录信息</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">使用系统级加密工具保护配置文件</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li></ul>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">四、第三方组件</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">4.1集成的大漠插件(dm.dll)需遵守其官方授权条款<br />4.2 开发者不承担因插件导致的：</span><span style=\" font-size:13px;\">                                                                        </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">游戏客户端异常</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">系统兼容性问题</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">反作弊机制触发的风险</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li></ul>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">五、免责条款</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">出现以下情况时开发者不承担责任：</span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">因软件漏洞导致的游戏数据异常</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">未及时更新导致的版本不兼容</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">用户自行修改代码引发的故障</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li>\n"
"<li style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13px;\">网络延迟或中断导致的登录失败</span><span style=\" font-family:\'SimSun\'; font-size:13px;\">                                     </span></li></ul>\n"
"<h4 style=\" margin-top:15px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#2c3e50;\">六、法律管辖</span><span style=\" font-size:medium; font-weight:600;\">                                     </span></h4>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt;\">6.1 本协议适用中华人民共和国法律<br />6.2 争议应优先通过友好协商解决<br />6.3 协商不成时应向开发者所在地法院提起诉讼                                    </span><span style=\" font-size:13px;\">                                     </span></p>\n"
"<p style=\" margin-top:30px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600;\">【再次提醒】本软件不会通过任何渠道收费，谨防受骗！</span><span style=\" font-size:13px; font-weight:600;\"> </span><span style=\" font-size:13px;\">                                    </span></p>\n"
"<p style=\" margin-top:30px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:13pt; font-weight:600; color:#e74c3c;\">【最终确认】继续使用即视为已阅读并同意上述所有条款</span><span style=\" font-size:13px; font-weight:600;\"> </span><span style=\" font-size:13px;\">                                </span></p></body></html>"))
