# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SpeedControlWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeedControlWindow(object):
    def setupUi(self, SpeedControlWindow):
        SpeedControlWindow.setObjectName("SpeedControlWindow")
        SpeedControlWindow.resize(300, 150)
        self.textEdit_speed = QtWidgets.QLineEdit(SpeedControlWindow)
        self.textEdit_speed.setGeometry(QtCore.QRect(20, 20, 260, 30))
        self.textEdit_speed.setStyleSheet("            /* 输入框样式 */\n"
"            QLineEdit {\n"
"                border: 1px solid #D8DEE9;\n"
"                padding: 5px;\n"
"                border-radius: 3px;\n"
"            }")
        self.textEdit_speed.setObjectName("textEdit_speed")
        self.buttonBox = QtWidgets.QDialogButtonBox(SpeedControlWindow)
        self.buttonBox.setGeometry(QtCore.QRect(50, 90, 201, 51))
        self.buttonBox.setStyleSheet("            /* 按钮通用样式 */\n"
"            QPushButton {\n"
"                background-color: #5E81AC;\n"
"                color: white;\n"
"                border: none;\n"
"                padding: 8px 15px;\n"
"                border-radius: 4px;\n"
"                min-width: 50px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: #81A1C1;\n"
"            }\n"
"\n"
"            QPushButton:pressed {\n"
"                background-color: #4C6A8C;\n"
"            }")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalSlider = QtWidgets.QSlider(SpeedControlWindow)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 70, 260, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(SpeedControlWindow)
        QtCore.QMetaObject.connectSlotsByName(SpeedControlWindow)

    def retranslateUi(self, SpeedControlWindow):
        _translate = QtCore.QCoreApplication.translate
        SpeedControlWindow.setWindowTitle(_translate("SpeedControlWindow", "变速"))
        self.textEdit_speed.setPlaceholderText(_translate("SpeedControlWindow", "请输入倍数"))

        # 设置按钮文本为中文
        ok_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel)
        ok_button.setText(_translate("SpeedWindow", "确定"))
        cancel_button.setText(_translate("SpeedWindow", "取消"))