# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SpeedControlWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeedControlWindow(object):
    def setupUi(self, SpeedWindow):
        SpeedWindow.setObjectName("SpeedWindow")
        SpeedWindow.resize(300, 150)
        self.textEdit_speed = QtWidgets.QLineEdit(SpeedWindow)
        self.textEdit_speed.setGeometry(QtCore.QRect(20, 20, 260, 30))
        self.textEdit_speed.setObjectName("textEdit_speed")
        self.buttonBox = QtWidgets.QDialogButtonBox(SpeedWindow)
        self.buttonBox.setGeometry(QtCore.QRect(50, 90, 181, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalSlider = QtWidgets.QSlider(SpeedWindow)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 70, 260, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(SpeedWindow)
        self.buttonBox.accepted.connect(SpeedWindow.accept)
        self.buttonBox.rejected.connect(SpeedWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(SpeedWindow)

    def retranslateUi(self, SpeedWindow):
        _translate = QtCore.QCoreApplication.translate
        SpeedWindow.setWindowTitle(_translate("SpeedWindow", "变速"))
        self.textEdit_speed.setPlaceholderText(_translate("SpeedWindow", "请输入倍数"))

        # 设置按钮文本为中文
        ok_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok)
        cancel_button = self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel)
        ok_button.setText(_translate("SpeedWindow", "确定"))
        cancel_button.setText(_translate("SpeedWindow", "取消"))
